### ISSUE TITLE
Diffchecking normal text?

### ISSUE THREAD

**Issue by blackpeasy** [ivan-lednev/obsidian-automatic-changelog#3]
Hello, would it be possible to include the possibility for diffchecking normal bouts of text in Obsidian?
like diffchecker: https://www.diffchecker.com/

**Comment by lucaslrodri** [comment]
This project uses `diff2html`, that mainly implements diff to git/files, I believe that if add the option to work with Google's `diff-match-patch` (or `diff-match-patch-es` for ESM and typescript implementation) it is possible to implement it.

Suggestion of implementation:

````markdown
```show-diff
text-from:
  this is the text before the modification
text-to:
  this is the text after the modification
```
````

PS: I don't know how to program a obsidian plugin, therefore I can't implement it

**Comment by ivan-lednev** [comment]
Hello, @blackpeasy, this plugin is focused on working with Git diffs, so closing this as not planned.
